Repository Team-Capple/Qapple-iOS, pull requests merged in 2024-09, with the labels that each got.

#167 [Feat] CommentView Usecase 작성
  Qapple/Qapple.xcodeproj/project.pbxproj
  Qapple/Qapple/Presentation/CommentView/CommentCell.swift
  Qapple/Qapple/Presentation/CommentView/CommentUseCase.swift
  Qapple/Qapple/Presentation/CommentView/CommentView.swift
  Qapple/Qapple/Presentation/Helper/NavigationRouter.swift
  Qapple/Qapple/Resource/Font/Font+Extension.swift
  Qapple/Qapple/Resource/Font/Pretendard-Light.otf
Labels: Feat, PR-Reviewing

#169 [Fix#168] 프로필 수정 이미지 변경
  Qapple/Qapple/Presentation/ProfileEditView/View/ProfileEditView.swift
Labels: Fix, PR-Reviewing

#171 [Feat/#170] 게시판 아카데미 일정 DayCounter 추가
  Qapple/Qapple/Component/Info/AcademyPlanDayCounter.swift
  Qapple/Qapple/Presentation/BulletinBoardView/BulletinBoardUseCase.swift
  Qapple/Qapple/Presentation/BulletinBoardView/BulletinBoardView.swift
Labels: Feat, PR-Reviewing

#174 [#172] timeAgo DateFormatter 로직 수정
  Qapple/Qapple/Extension/Date+Extension.swift
  Qapple/Qapple/Presentation/CommentView/CommentUseCase.swift
Labels: Fix, PR-Reviewing

#175 [Feat] 오늘의 질문 UI 업데이트
  Qapple/Qapple/Domain/Entity/Answer.swift
  Qapple/Qapple/Presentation/AnswerListView/View/AnswerListView.swift
  Qapple/Qapple/Presentation/TodayQuestionView/View/AnswerCell.swift
  Qapple/Qapple/Presentation/TodayQuestionView/View/TodayQuestionView.swift
  Qapple/Qapple/Presentation/TodayQuestionView/ViewModel/TodayQuestionViewModel.swift
  Qapple/Qapple/Presentation/WrittenAnswerView/WrittenAnswerView.swift
Labels: Feat, PR-Reviewing

#177 [Feat] 알림 UI 업데이트
  Qapple/Qapple/Presentation/NotificationView/NotificationCell.swift
  Qapple/Qapple/Presentation/NotificationView/NotificationUseCase.swift
Labels: Feat, PR-Reviewing

#184 [#183] SignIn, SignUp API 업데이트 내용 적용
  Qapple/Qapple/App/AppDelegate.swift
  Qapple/Qapple/Data/Network/DataMapping/Request/MemberRequest.swift
  Qapple/Qapple/Data/Network/DataMapping/SignInInfo.swift
  Qapple/Qapple/Data/Network/NetworkManager+Member.swift
  Qapple/Qapple/Data/Network/NetworkManager+Question.swift
  Qapple/Qapple/Presentation/SignInView/ViewModel/AuthViewModel.swift
Labels: Feat, PR-Reviewing

#182 #181 / 댓글View api 연결(댓글 불러오기), ApiEndPoints 추가, 모델 수정
  Qapple/Qapple.xcodeproj/project.pbxproj
  Qapple/Qapple/Data/Network/DataMapping/ApiEndpoints.swift
  Qapple/Qapple/Data/Network/DataMapping/Request/CommentRequest.swift
  Qapple/Qapple/Data/Network/DataMapping/Response/CommentResponse.swift
  Qapple/Qapple/Data/Network/NetworkManager + Comment.swift
  Qapple/Qapple/Domain/Entity/Post.swift
  Qapple/Qapple/Presentation/BulletinBoardView/BulletinBoardCell.swift
  Qapple/Qapple/Presentation/CommentView/CommentCell.swift
  Qapple/Qapple/Presentation/CommentView/CommentUseCase.swift
  Qapple/Qapple/Presentation/CommentView/CommentView.swift
  Qapple/Qapple/Presentation/CommentView/CommentViewModel.swift
  Qapple/Qapple/Presentation/Helper/NavigationRouter.swift
Labels: Feat, PR-Reviewing

#186 [Fix] CommentCell 이름 익명화 되도록 수정
  Qapple/Qapple/Data/Network/DataMapping/Response/CommentResponse.swift
  Qapple/Qapple/Presentation/CommentView/CommentCell.swift
  Qapple/Qapple/Presentation/CommentView/CommentView.swift
  Qapple/Qapple/Presentation/CommentView/CommentViewModel.swift
Labels: Fix, PR-Reviewing

#180 [Feat] 게시판View API 연결
  Qapple/Qapple.xcodeproj/project.pbxproj
  Qapple/Qapple/Data/Network/DataMapping/ApiEndpoints.swift
  Qapple/Qapple/Data/Network/DataMapping/Request/BoardRequest.swift
  Qapple/Qapple/Data/Network/DataMapping/Response/BoardResponse.swift
  Qapple/Qapple/Data/Network/NetworkManager+Board.swift
  Qapple/Qapple/Extension/String+Extension.swift
  Qapple/Qapple/Presentation/BulletinBoardView/BulletinBoardUseCase.swift
  Qapple/Qapple/Presentation/BulletinBoardView/BulletinBoardView.swift
  Qapple/Qapple/Presentation/BulletinPostingView/BulletinPostingUseCase.swift
  Qapple/Qapple/Presentation/BulletinPostingView/BulletinPostingView.swift
  Qapple/Qapple/Presentation/TodayQuestionView/ViewModel/TodayQuestionViewModel.swift
Labels: Feat, PR-Reviewing

#189 [Fix] 변수 선언 키워드 변경
  Qapple/Qapple/Presentation/BulletinBoardView/BulletinBoardUseCase.swift
Labels: Fix, PR-Reviewing

#192 [Feat] BolletinBoard 화면 업데이트 관련
  Qapple/Qapple/Presentation/BulletinBoardView/BulletinBoardUseCase.swift
  Qapple/Qapple/Presentation/BulletinBoardView/BulletinBoardView.swift
Labels: Feat, PR-Merged

#195 [Fix] 댓글뷰의 boardId와 게시글 id와 연결
  Qapple/Qapple/Presentation/CommentView/CommentCell.swift
  Qapple/Qapple/Presentation/CommentView/CommentView.swift
Labels: Fix, PR-Reviewing

#199 [#198] Navigation & TabBar 애니메이션 버그 수정
  Qapple/Qapple.xcodeproj/project.pbxproj
  Qapple/Qapple/App/QappleApp.swift
  Qapple/Qapple/Presentation/BulletinBoardView/BulletinBoardView.swift
  Qapple/Qapple/Presentation/BulletinSearchView/BulletinSearchView.swift
  Qapple/Qapple/Presentation/Helper/NavigationRouter.swift
  Qapple/Qapple/Presentation/MyPageView/View/MyPageView.swift
  Qapple/Qapple/Presentation/SignInView/View/MainView.swift
Labels: Feat, PR-Reviewing

#203 [Feat] 오늘의 질문 API 업데이트
  Qapple/Qapple.xcodeproj/project.pbxproj
  Qapple/Qapple.xcodeproj/xcshareddata/xcschemes/Qapple.xcscheme
  Qapple/Qapple/Data/Network/DataMapping/Request/AnswerRequest.swift
  Qapple/Qapple/Data/Network/DataMapping/Response/AnswerResponse.swift
  Qapple/Qapple/Data/Network/DataMapping/Response/QuestionResponse.swift
  Qapple/Qapple/Data/Network/NetworkManager+Answer.swift
  Qapple/Qapple/Data/Network/NetworkManager+Question.swift
  Qapple/Qapple/Domain/Entity/Answer.swift
  Qapple/Qapple/Extension/UINavigationController+Extension.swift
  Qapple/Qapple/Presentation/AnswerListView/View/AnswerListView.swift
  Qapple/Qapple/Presentation/AnswerListView/ViewModel/TodayAnswerViewModel.swift
  Qapple/Qapple/Presentation/AnswerView/View/AnswerView.swift
  Qapple/Qapple/Presentation/AnswerView/ViewModel/AnswerViewModel.swift
  Qapple/Qapple/Presentation/CompleteAnswerView/CompleteAnswerView.swift
  Qapple/Qapple/Presentation/SignInView/View/MainView.swift
  Qapple/Qapple/Presentation/TodayQuestionListView/View/QuestionCell.swift
  Qapple/Qapple/Presentation/TodayQuestionListView/View/TodayQuestionListView.swift
  Qapple/Qapple/Presentation/TodayQuestionListView/ViewModel/QuestionViewModel.swift
  Qapple/Qapple/Presentation/TodayQuestionView/View/AnswerCell.swift
  Qapple/Qapple/Presentation/TodayQuestionView/View/TodayQuestionActionButton.swift
  Qapple/Qapple/Presentation/TodayQuestionView/View/TodayQuestionView.swift
  Qapple/Qapple/Presentation/TodayQuestionView/ViewModel/TodayQuestionViewModel.swift
  Qapple/Qapple/Presentation/WrittenAnswerView/WrittenAnswerView.swift
  Qapple/Qapple/Presentation/WrittenAnswerView/WrittenAnswerViewModel.swift
Labels: Feat, PR-Reviewing

#202 [Feat] 게시판 api 변경 & 로딩화면 구현
  Qapple/Qapple/Data/Network/DataMapping/ApiEndpoints.swift
  Qapple/Qapple/Data/Network/DataMapping/Request/BoardRequest.swift
  Qapple/Qapple/Data/Network/DataMapping/Request/ReportRequest.swift
  Qapple/Qapple/Data/Network/DataMapping/Response/BoardResponse.swift
  Qapple/Qapple/Data/Network/DataMapping/Response/ReportResponse.swift
  Qapple/Qapple/Data/Network/NetworkManager+Board.swift
  Qapple/Qapple/Data/Network/NetworkManager+Report.swift
  Qapple/Qapple/Domain/Entity/Post.swift
  Qapple/Qapple/Presentation/BulletinBoardView/BulletinBoardCell.swift
  Qapple/Qapple/Presentation/BulletinBoardView/BulletinBoardSeeMoreSheetView.swift
  Qapple/Qapple/Presentation/BulletinBoardView/BulletinBoardUseCase.swift
  Qapple/Qapple/Presentation/BulletinBoardView/BulletinBoardView.swift
  Qapple/Qapple/Presentation/BulletinPostingView/BulletinPostingUseCase.swift
  Qapple/Qapple/Presentation/BulletinPostingView/BulletinPostingView.swift
  Qapple/Qapple/Presentation/BulletinSearchView/BulletinSearchView.swift
  Qapple/Qapple/Presentation/CommentView/CommentCell.swift
  Qapple/Qapple/Presentation/CommentView/CommentView.swift
  Qapple/Qapple/Presentation/Helper/NavigationRouter.swift
  Qapple/Qapple/Presentation/Helper/ReportType.swift
  Qapple/Qapple/Presentation/ReportView/View/ReportView.swift
Labels: Feat, PR-Merged

#207 [ Feat] 오늘의 질문 QA 내용 업데이트
  Qapple/Qapple/Domain/Entity/Answer.swift
  Qapple/Qapple/Presentation/AnswerListView/View/AnswerListView.swift
  Qapple/Qapple/Presentation/AnswerListView/ViewModel/TodayAnswerViewModel.swift
  Qapple/Qapple/Presentation/BulletinBoardView/BulletinBoardView.swift
  Qapple/Qapple/Presentation/SignInView/View/MainView.swift
  Qapple/Qapple/Presentation/TodayQuestionView/View/AnswerCell.swift
  Qapple/Qapple/Presentation/TodayQuestionView/View/TodayQuestionActionButton.swift
  Qapple/Qapple/Presentation/TodayQuestionView/View/TodayQuestionView.swift
  Qapple/Qapple/Presentation/TodayQuestionView/ViewModel/TodayQuestionViewModel.swift
  Qapple/Qapple/Presentation/WrittenAnswerView/WrittenAnswerView.swift
Labels: Feat, PR-Reviewing

#208 [Feat] 댓글 API 업데이트, 신고 삭제 기능 구현
  Qapple/Qapple.xcodeproj/project.pbxproj
  Qapple/Qapple/Data/Network/DataMapping/ApiEndpoints.swift
  Qapple/Qapple/Data/Network/DataMapping/Request/CommentRequest.swift
  Qapple/Qapple/Data/Network/DataMapping/Response/CommentResponse.swift
  Qapple/Qapple/Data/Network/NetworkManager + Comment.swift
  Qapple/Qapple/Presentation/CommentView/CommentCell.swift
  Qapple/Qapple/Presentation/CommentView/CommentReportView.swift
  Qapple/Qapple/Presentation/CommentView/CommentView.swift
  Qapple/Qapple/Presentation/CommentView/CommentViewModel.swift
  Qapple/Qapple/Presentation/Helper/CommentReportType.swift
  Qapple/Qapple/Presentation/Helper/NavigationRouter.swift
Labels: Feat, PR-Merged

#212 [Feat] 댓글 QA 수정
  Qapple/Qapple/Presentation/CommentView/CommentCell.swift
  Qapple/Qapple/Presentation/CommentView/CommentView.swift
Labels: Feat, PR-Merged

#213 [Feat] 게시글 QA 반영 1차
  Qapple/Qapple/Presentation/BulletinBoardView/BulletinBoardCell.swift
  Qapple/Qapple/Presentation/BulletinBoardView/BulletinBoardUseCase.swift
  Qapple/Qapple/Presentation/BulletinBoardView/BulletinBoardView.swift
  Qapple/Qapple/Presentation/BulletinPostingView/BulletinPostingUseCase.swift
  Qapple/Qapple/Presentation/BulletinPostingView/BulletinPostingView.swift
  Qapple/Qapple/Presentation/CommentView/CommentView.swift
Labels: Feat, PR-Reviewing

#214 [Feat] Notification API 연결 및 추가 QA 작업
  Qapple/Qapple.xcodeproj/project.pbxproj
  Qapple/Qapple/Data/Network/DataMapping/ApiEndpoints.swift
  Qapple/Qapple/Data/Network/DataMapping/Request/NotificationRequest.swift
  Qapple/Qapple/Data/Network/DataMapping/Response/NotificationResponse.swift
  Qapple/Qapple/Data/Network/NetworkManager+Comment.swift
  Qapple/Qapple/Data/Network/NetworkManager+Notification.swift
  Qapple/Qapple/Domain/Entity/QappleNoti.swift
  Qapple/Qapple/Presentation/Helper/MailView.swift
  Qapple/Qapple/Presentation/MyPageView/View/MyPageView.swift
  Qapple/Qapple/Presentation/MyPageView/ViewModel/MyPageViewModel.swift
  Qapple/Qapple/Presentation/NotificationView/NotificationCell.swift
  Qapple/Qapple/Presentation/NotificationView/NotificationListView.swift
  Qapple/Qapple/Presentation/NotificationView/NotificationUseCase.swift
  Qapple/Qapple/Presentation/ProfileEditView/View/ProfileEditView.swift
  Qapple/Qapple/Presentation/ProfileEditView/ViewModel/ProfileEditViewModel.swift
  Qapple/Qapple/Presentation/SignUpView/View/SignUpAuthCodeView.swift
  Qapple/Qapple/Presentation/SignUpView/View/SignUpEmailView.swift
  Qapple/Qapple/Presentation/TodayQuestionListView/View/TodayQuestionListView.swift
  Qapple/Qapple/Presentation/TodayQuestionView/View/TodayQuestionView.swift
Labels: Feat, PR-Reviewing

#218 [Feat] 신고 화면 로딩 추가
  Qapple/Qapple/Presentation/CommentView/CommentReportView.swift
  Qapple/Qapple/Presentation/ReportView/View/ReportView.swift
Labels: Feat, PR-Merged

#219 [Feat] 댓글 ellipsis 구현
  Qapple/Qapple/Presentation/BulletinBoardView/BulletinBoardCell.swift
  Qapple/Qapple/Presentation/BulletinBoardView/BulletinBoardSeeMoreSheetView.swift
  Qapple/Qapple/Presentation/BulletinBoardView/BulletinBoardView.swift
  Qapple/Qapple/Presentation/BulletinSearchView/BulletinSearchView.swift
  Qapple/Qapple/Presentation/CommentView/CommentReportView.swift
  Qapple/Qapple/Presentation/CommentView/CommentView.swift
  Qapple/Qapple/Presentation/Helper/NavigationRouter.swift
  Qapple/Qapple/Presentation/ReportView/View/ReportView.swift
  Qapple/Qapple/Presentation/SeeMoreView/View/SeeMoreView.swift
Labels: Feat, PR-Merged

#221 [Feat] 댓글 뷰 햅틱 추가
  Qapple/Qapple/Presentation/CommentView/CommentCell.swift
  Qapple/Qapple/Presentation/CommentView/CommentView.swift
  Qapple/Qapple/Presentation/CommentView/CommentViewModel.swift
Labels: Feat, PR-Reviewing

#223 [Feat] 게시글 햅틱 추가
  Qapple/Qapple/Presentation/BulletinBoardView/BulletinBoardCell.swift
  Qapple/Qapple/Presentation/BulletinBoardView/BulletinBoardSeeMoreSheetView.swift
  Qapple/Qapple/Presentation/BulletinBoardView/BulletinBoardView.swift
  Qapple/Qapple/Presentation/BulletinPostingView/BulletinPostingView.swift
Labels: Feat, PR-Merged

#224 [Fix] 자동 로그인 로직 수정
  Qapple/Qapple.xcodeproj/project.pbxproj
  Qapple/Qapple/App/AppDelegate.swift
  Qapple/Qapple/App/QappleApp.swift
  Qapple/Qapple/Data/AppleLogin/AppleLoginService.swift
  Qapple/Qapple/Data/Network/DataMapping/ApiEndpoints.swift
  Qapple/Qapple/Data/Network/DataMapping/Response/TokenResponse.swift
  Qapple/Qapple/Data/Network/NetworkManager+Member.swift
  Qapple/Qapple/Data/Network/NetworkManager+Token.swift
  Qapple/Qapple/Presentation/SignInView/View/MainView.swift
  Qapple/Qapple/Presentation/SignInView/ViewModel/AuthViewModel.swift
  Qapple/Qapple/Presentation/TodayQuestionView/ViewModel/TodayQuestionViewModel.swift
Labels: Fix, PR-Reviewing

#226 [Chore] 로딩&문구 변경
  Qapple/Qapple/Presentation/BulletinBoardView/BulletinBoardView.swift
  Qapple/Qapple/Presentation/MyPageView/View/MyPageView.swift
Labels: Chore, PR-Reviewing

#228 [Feat] 로딩중일때 refresh 안되게 수정
  Qapple/Qapple/Presentation/CommentView/CommentView.swift
Labels: Fix, PR-Reviewing

#230 [Fix] Notification API 업데이트
  Qapple/Qapple/Data/Network/DataMapping/Response/NotificationResponse.swift
  Qapple/Qapple/Data/Network/NetworkManager+Notification.swift
  Qapple/Qapple/Presentation/NotificationView/NotificationUseCase.swift
Labels: Fix, PR-Reviewing

#232 [Feat] 페이지네이션 적용
  Qapple/Qapple/Data/Network/DataMapping/Request/AnswerRequest.swift
  Qapple/Qapple/Data/Network/NetworkManager+Answer.swift
  Qapple/Qapple/Data/Network/NetworkManager+Comment.swift
  Qapple/Qapple/Presentation/AnswerListView/View/AnswerListView.swift
  Qapple/Qapple/Presentation/AnswerListView/ViewModel/TodayAnswerViewModel.swift
  Qapple/Qapple/Presentation/AnswerView/ViewModel/AnswerViewModel.swift
  Qapple/Qapple/Presentation/BulletinBoardView/BulletinBoardUseCase.swift
  Qapple/Qapple/Presentation/BulletinBoardView/BulletinBoardView.swift
  Qapple/Qapple/Presentation/BulletinPostingView/BulletinPostingView.swift
  Qapple/Qapple/Presentation/BulletinSearchView/BulletinSearchView.swift
  Qapple/Qapple/Presentation/CommentView/CommentCell.swift
  Qapple/Qapple/Presentation/CommentView/CommentView.swift
  Qapple/Qapple/Presentation/CommentView/CommentViewModel.swift
  Qapple/Qapple/Presentation/NotificationView/NotificationListView.swift
  Qapple/Qapple/Presentation/NotificationView/NotificationUseCase.swift
  Qapple/Qapple/Presentation/TodayQuestionListView/View/TodayQuestionListView.swift
  Qapple/Qapple/Presentation/TodayQuestionListView/ViewModel/QuestionViewModel.swift
  Qapple/Qapple/Presentation/TodayQuestionView/ViewModel/TodayQuestionViewModel.swift
  Qapple/Qapple/Presentation/WrittenAnswerView/WrittenAnswerView.swift
  Qapple/Qapple/Presentation/WrittenAnswerView/WrittenAnswerViewModel.swift
Labels: Feat, PR-Reviewing

#234 [Feat] QA 내용 반영
  Qapple/Qapple.xcodeproj/project.pbxproj
  Qapple/Qapple/Component/Input/SearchBar.swift
  Qapple/Qapple/Component/TabBar/TabType.swift
  Qapple/Qapple/Data/Network/DataMapping/Request/BoardRequest.swift
  Qapple/Qapple/Data/Network/DataMapping/Response/BoardResponse.swift
  Qapple/Qapple/Data/Network/NetworkManager+Board.swift
  Qapple/Qapple/Extension/Date+Extension.swift
  Qapple/Qapple/Presentation/AnswerView/View/AnswerView.swift
  Qapple/Qapple/Presentation/BulletinBoardView/BulletinBoardUseCase.swift
  Qapple/Qapple/Presentation/BulletinBoardView/BulletinBoardView.swift
  Qapple/Qapple/Presentation/BulletinSearchView/BulletinSearchView.swift
  Qapple/Qapple/Presentation/Helper/MailView.swift
  Qapple/Qapple/Presentation/Helper/PrivacyDocument.swift
  Qapple/Qapple/Presentation/Manager/NotificationManager.swift
  Qapple/Qapple/Presentation/MyPageView/View/MyPageSection.swift
  Qapple/Qapple/Presentation/MyPageView/View/MyPageSectionCell.swift
  Qapple/Qapple/Presentation/MyPageView/View/MyPageSectionTitle.swift
  Qapple/Qapple/Presentation/MyPageView/View/MyPageView.swift
  Qapple/Qapple/Presentation/MyPageView/View/MyProfileSummary.swift
  Qapple/Qapple/Presentation/SignInView/View/MainView.swift
  Qapple/Qapple/Presentation/TodayQuestionListView/View/QuestionCell.swift
  Qapple/Qapple/Presentation/WrittenAnswerView/WrittenAnswerView.swift
Labels: Feat, PR-Reviewing

#236 [Feat] 댓글 뷰 QA 두번째
  Qapple/Qapple/Data/Network/DataMapping/Response/CommentResponse.swift
  Qapple/Qapple/Presentation/CommentView/CommentCell.swift
  Qapple/Qapple/Presentation/CommentView/CommentReportView.swift
  Qapple/Qapple/Presentation/CommentView/CommentView.swift
  Qapple/Qapple/Presentation/CommentView/CommentViewModel.swift
  Qapple/Qapple/Presentation/Helper/NavigationRouter.swift
  Qapple/Qapple/Resource/Color/Colors.xcassets/Text/sub5.colorset/Contents.json
Labels: Feat, PR-Reviewing
