Repository Team-Capple/Qapple-iOS, pull requests merged in 2024-08, with the labels that each got.

#126 [Feat] Comment Cell 및 Comment View 구현
  Qapple/Qapple.xcodeproj/project.pbxproj
  Qapple/Qapple/Presentation/CommentView/CommentCell.swift
  Qapple/Qapple/Presentation/CommentView/CommentView.swift
Labels: Feat, PR-Merged

#128 [FEAT] 게시판(BulletinBoardView) View 구현
  Qapple/Qapple.xcodeproj/project.pbxproj
  Qapple/Qapple/App/CappleApp.swift
  Qapple/Qapple/Component/Info/AcademyPlanDayCounter.swift
  Qapple/Qapple/Component/Toolbar/CustomToolbarItem.swift
  Qapple/Qapple/Domain/Entity/DummyModel.swift
  Qapple/Qapple/Domain/Entity/Post.swift
  Qapple/Qapple/Presentation/BulletinBoardView/BulletinBoardCell.swift
  Qapple/Qapple/Presentation/BulletinBoardView/BulletinBoardSeeMoreSheetView.swift
  Qapple/Qapple/Presentation/BulletinBoardView/BulletinBoardUseCase.swift
  Qapple/Qapple/Presentation/BulletinBoardView/BulletinBoardView.swift
  Qapple/Qapple/Resource/Assets.xcassets/3DImage/calendar.imageset/Contents.json
  Qapple/Qapple/Resource/Assets.xcassets/3DImage/calendar.imageset/Frame 427318974.png
  Qapple/Qapple/Resource/Font/Font+Extension.swift
Labels: Feat, PR-Reviewing

#136 Feat/#129 bulletin search view
  Qapple/Qapple.xcodeproj/project.pbxproj
  Qapple/Qapple/App/CappleApp.swift
  Qapple/Qapple/Component/Info/AcademyPlanDayCounter.swift
  Qapple/Qapple/Component/Input/SearchBar.swift
  Qapple/Qapple/Component/Toolbar/CustomToolbarItem.swift
  Qapple/Qapple/Domain/Entity/DummyModel.swift
  Qapple/Qapple/Domain/Entity/Post.swift
  Qapple/Qapple/Presentation/BulletinBoardView/BulletinBoardCell.swift
  Qapple/Qapple/Presentation/BulletinBoardView/BulletinBoardSeeMoreSheetView.swift
  Qapple/Qapple/Presentation/BulletinBoardView/BulletinBoardUseCase.swift
  Qapple/Qapple/Presentation/BulletinBoardView/BulletinBoardView.swift
  Qapple/Qapple/Presentation/BulletinSearchView/BulletinSearchView.swift
  Qapple/Qapple/Resource/Assets.xcassets/3DImage/calendar.imageset/Contents.json
  Qapple/Qapple/Resource/Assets.xcassets/3DImage/calendar.imageset/Frame 427318974.png
  Qapple/Qapple/Resource/Font/Font+Extension.swift
Labels: Feat, PR-Merged

#139 [Fix/#138] BulletinPostingView Conflict 해결
  Qapple/Qapple.xcodeproj/project.pbxproj
  Qapple/Qapple/Presentation/BulletinPostingView/BulletinPostingUseCase.swift
  Qapple/Qapple/Presentation/BulletinPostingView/BulletinPostingView.swift
Labels: Fix, PR-InProgress

#143 [#133] 충돌 해결
  Qapple/Qapple.xcodeproj/project.pbxproj
  Qapple/Qapple/Data/Network/DataMapping/Response/AnswerResponse.swift
  Qapple/Qapple/Domain/Entity/DTO.swift
  Qapple/Qapple/Presentation/Helper/MainPathModel.swift
  Qapple/Qapple/Presentation/NotificationView/NotificationCell.swift
  Qapple/Qapple/Presentation/NotificationView/NotificationListView.swift
  Qapple/Qapple/Presentation/NotificationView/NotificationUseCase.swift
  Qapple/Qapple/Presentation/SearchResultView/View/QuestionCell.swift
  Qapple/Qapple/Presentation/SearchResultView/View/SearchResultView.swift
  Qapple/Qapple/Presentation/SignInView/View/MainView.swift
  Qapple/Qapple/Presentation/TodayAnswersView/Model/SingleAnswerModel.swift
  Qapple/Qapple/Presentation/TodayAnswersView/View/SingleAnswerView.swift
  Qapple/Qapple/Presentation/TodayAnswersView/View/TodayAnswerView.swift
  Qapple/Qapple/Presentation/TodayQuestionView/View/AnswerCell.swift
  Qapple/Qapple/Presentation/TodayQuestionView/View/TodayQuestionView.swift
  Qapple/Qapple/Presentation/WrittenAnswerView/WrittenAnswerView.swift
Labels: Fix

#144 [Fix] developCopy 반영
  Qapple/Qapple.xcodeproj/project.pbxproj
  Qapple/Qapple/Data/Network/DataMapping/Response/AnswerResponse.swift
  Qapple/Qapple/Domain/Entity/DTO.swift
  Qapple/Qapple/Presentation/Helper/MainPathModel.swift
  Qapple/Qapple/Presentation/NotificationView/NotificationCell.swift
  Qapple/Qapple/Presentation/NotificationView/NotificationListView.swift
  Qapple/Qapple/Presentation/NotificationView/NotificationUseCase.swift
  Qapple/Qapple/Presentation/SearchResultView/View/QuestionCell.swift
  Qapple/Qapple/Presentation/SearchResultView/View/SearchResultView.swift
  Qapple/Qapple/Presentation/SignInView/View/MainView.swift
  Qapple/Qapple/Presentation/TodayAnswersView/Model/SingleAnswerModel.swift
  Qapple/Qapple/Presentation/TodayAnswersView/View/SingleAnswerView.swift
  Qapple/Qapple/Presentation/TodayAnswersView/View/TodayAnswerView.swift
  Qapple/Qapple/Presentation/TodayQuestionView/View/AnswerCell.swift
  Qapple/Qapple/Presentation/TodayQuestionView/View/TodayQuestionView.swift
  Qapple/Qapple/Presentation/WrittenAnswerView/WrittenAnswerView.swift
Labels: Fix

#142 [Feat/#141] TabBar 컴포넌트 구현
  Qapple/Qapple.xcodeproj/project.pbxproj
  Qapple/Qapple/App/CappleApp.swift
  Qapple/Qapple/Component/TabBar/TabBar.swift
  Qapple/Qapple/Component/TabBar/TabType.swift
Labels: Feat, PR-Reviewing

#146 [Feat/#145] DeviceToken 로그 기능 구현
  Qapple/Qapple.xcodeproj/project.pbxproj
  Qapple/Qapple/App/AppDelegate.swift
  Qapple/Qapple/App/CappleApp.swift
  Qapple/Qapple/Data/AppleLogin/AppleLoginService.swift
  Qapple/Qapple/Presentation/SignInView/ViewModel/AuthViewModel.swift
  Qapple/Qapple/Presentation/TodayQuestionView/ViewModel/TodayQuestionViewModel.swift
Labels: Feat, PR-Reviewing

#149 [Feat] FCM & APNs 구현
  Qapple/Qapple.xcodeproj/project.pbxproj
  Qapple/Qapple/App/AppDelegate.swift
  Qapple/Qapple/GoogleService-Info.plist
  Qapple/Qapple/Info.plist
Labels: Feat, PR-Reviewing

#150 [Feat/#147] navigation path
  Qapple/Qapple.xcodeproj/project.pbxproj
  Qapple/Qapple/App/CappleApp.swift
  Qapple/Qapple/Component/TabBar/TabBar.swift
  Qapple/Qapple/Presentation/AnswerView/View/AnswerView.swift
  Qapple/Qapple/Presentation/BulletinBoardView/BulletinBoardView.swift
  Qapple/Qapple/Presentation/BulletinPostingView/BulletinPostingView.swift
  Qapple/Qapple/Presentation/BulletinSearchView/BulletinSearchView.swift
  Qapple/Qapple/Presentation/CompleteAnswerView/CompleteAnswerView.swift
  Qapple/Qapple/Presentation/Helper/MainPathModel.swift
  Qapple/Qapple/Presentation/Helper/NavigationRouter.swift
  Qapple/Qapple/Presentation/MyPageView/View/MyPageView.swift
  Qapple/Qapple/Presentation/NotificationView/NotificationListView.swift
  Qapple/Qapple/Presentation/ProfileEditView/View/ProfileEditView.swift
  Qapple/Qapple/Presentation/ReportView/View/ReportView.swift
  Qapple/Qapple/Presentation/SearchResultView/View/QuestionCell.swift
  Qapple/Qapple/Presentation/SearchResultView/View/SearchResultView.swift
  Qapple/Qapple/Presentation/SeeMoreView/View/SeeMoreView.swift
  Qapple/Qapple/Presentation/SignInView/View/MainView.swift
  Qapple/Qapple/Presentation/TodayAnswersView/View/TodayAnswerView.swift
  Qapple/Qapple/Presentation/TodayQuestionView/View/TodayQuestionView.swift
  Qapple/Qapple/Presentation/WrittenAnswerView/WrittenAnswerView.swift
Labels: Feat, PR-Reviewing

#152 [Feat/#151] 기본 TabBar로 변경
  Qapple/Qapple.xcodeproj/project.pbxproj
  Qapple/Qapple/Presentation/BulletinBoardView/BulletinBoardView.swift
  Qapple/Qapple/Presentation/Helper/TodayQuestionTab.swift
  Qapple/Qapple/Presentation/SignInView/View/MainView.swift
Labels: Feat, PR-Reviewing

#156 [Feat] 질문리스트 UI 업데이트
  Qapple/Qapple/Presentation/SearchResultView/View/QuestionCell.swift
  Qapple/Qapple/Presentation/SearchResultView/View/SearchResultView.swift
Labels: Feat, PR-Reviewing

#164 [Feat/#162] TodayQuestion, AnswerList 업데이트
  Qapple/Qapple.xcodeproj/project.pbxproj
  Qapple/Qapple/Data/Network/DataMapping/Response/AnswerResponse.swift
  Qapple/Qapple/Domain/Entity/Answer.swift
  Qapple/Qapple/Presentation/AnswerListView/View/AnswerListView.swift
  Qapple/Qapple/Presentation/AnswerListView/View/KeywordSelector.swift
  Qapple/Qapple/Presentation/AnswerListView/ViewModel/TodayAnswerViewModel.swift
  Qapple/Qapple/Presentation/Helper/NavigationRouter.swift
  Qapple/Qapple/Presentation/SearchResultView/View/QuestionCell.swift
  Qapple/Qapple/Presentation/SearchResultView/View/SearchResultView.swift
  Qapple/Qapple/Presentation/SignInView/View/MainView.swift
  Qapple/Qapple/Presentation/TodayAnswersView/Model/SingleAnswerModel.swift
  Qapple/Qapple/Presentation/TodayQuestionView/View/AnswerCell.swift
  Qapple/Qapple/Presentation/TodayQuestionView/View/TodayQuestionView.swift
  Qapple/Qapple/Presentation/TodayQuestionView/ViewModel/TodayQuestionViewModel.swift
  Qapple/Qapple/Presentation/WrittenAnswerView/WrittenAnswerView.swift
Labels: Feat, PR-Reviewing

#160 [Feat/#158] 댓글 view UI 수정
  Qapple/Qapple/Presentation/CommentView/CommentCell.swift
  Qapple/Qapple/Presentation/CommentView/CommentView.swift
  Qapple/Qapple/Resource/Color/Colors.xcassets/State/delete.colorset/Contents.json
  Qapple/Qapple/Resource/Color/Colors.xcassets/State/report.colorset/Contents.json
Labels: Feat, PR-Reviewing

#161 [Feat] 알림View UI 업데이트
  Qapple/Qapple/Extension/Date+Extension.swift
  Qapple/Qapple/Presentation/AnswerListView/View/AnswerListView.swift
  Qapple/Qapple/Presentation/Helper/NavigationRouter.swift
  Qapple/Qapple/Presentation/NotificationView/NotificationCell.swift
  Qapple/Qapple/Presentation/NotificationView/NotificationListView.swift
  Qapple/Qapple/Presentation/NotificationView/NotificationUseCase.swift
Labels: Feat, PR-Reviewing

#165 [Feat] Navigation 수정
  Qapple/Qapple/Presentation/AnswerView/View/AnswerView.swift
  Qapple/Qapple/Presentation/BulletinBoardView/BulletinBoardCell.swift
  Qapple/Qapple/Presentation/BulletinBoardView/BulletinBoardView.swift
  Qapple/Qapple/Presentation/CommentView/CommentView.swift
  Qapple/Qapple/Presentation/Helper/NavigationRouter.swift
Labels: Feat, PR-Reviewing
